# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33f3056b1858b048c1d8f79d3cde9fab35847c5ccd377244a372e2d1a338e85435db5aff604aa3d39c7d06d621c505824fbcfbd726fe9295a844af71414561cf

test:
  secret_key_base: 2f53bacbd88f0a646b2c11516af3dd08140602a31a29901e28b9a330e8dfd79f3f4e1e3ef672808882e5a5bdd66c51df814814a51ba1acaa3028082be208d087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
